export const testCentres = [
    {state: "Andhra Pradesh", testcentre: ["Sri Venkateswara Institute of Medical Sciences in Tirupati", "GMC, Anantapur", "Siddhartha Medical College, Vijayawada", "Ranagaraya Medical College, Kakinada"]},
    {state: "Andaman and Nicobar", testcentre: ["Regional Medical Research Centre, Port Blair"]},
    {state: "Assam", testcentre: ["Gauhati Medical College, Guwahati", "Regional Medical Research Centre, Dibrugarh", "Silchar Medical College, Silchar", "Jorhat Medical College, Jorhat"]},
    {state: "Bihar", testcentre: ["Rajendra Memorial Research Institute of Medical Sciences, Patna"]},
    {state: "Chandigarh", testcentre: ["Post Graduate Institute of Medical Education & Research"]},
    {state: "Chhattisgarh", testcentre: ["AIIMS, Raipur"]},
    {state: "Delhi", testcentre: ["AIIMS"]},
    {state: "Gujarat", testcentre: ["BJ Medical College, Ahmedabad", "M P Shah Government Medical College, Jamnagar"]},
    {state: "Haryana", testcentre: ["Pt B D Sharma Post Graduate Institute of Medical Sciences, Rohtak", "BPS Government Medical College, Sonipat"]},
    {state: "Himachal Pradesh", testcentre: ["Indira Gandhi Medical College, Shimla", "Dr Rajendra Prasad Government Medical College, Kangra, Tanda"]},
    {state: "Jammu-Kashmir", testcentre: ["Sher-I-Kashmir Institute of Medical Sciences, Srinagar", "Government Medical College, Jammu", "Government Medical College, Srinagar"]},
    {state: "Jharkhand", testcentre: ["MGM Medical College, Jamshedpur"]},
    {state: "Karnataka", testcentre: ["Bangalore Medical College & Research Institute, Bengaluru", "National Institute of Virology Field Unit, Bengaluru", "Mysore Medical College & Research Institute, Mysore", "Hassan Institute of Medical Sciences, Hassan", "Shimoga Institute of Medical Sciences, Shivamoga"]},
    {state: "Kerala", testcentre: ["National Institute of Virology Field, Kerala Unit", "Government Medical College, Thriuvananthapuram", "Government Medical College, Kozhikhode", "Government Medical College, Thrissur"]},
    {state: "Madhya Pradesh", testcentre: ["AIIMS, Bhopal", "National Institute of Research in Tribal Health (NIRTH), Jabalpur"]},
    {state: "Maharashtra", testcentre: ["Indira Gandhi Government Medical College, Nagpur","Kasturba Hospital for Infectious Diseases, Mumbai", "NIV Mumbai Unit"]},
    {state: "Manipur", testcentre: ["JN Institute of Medical Sciences Hospital, Imphal", "Regional Institute of Medical Science, Imphal"]},
    {state: "Meghalaya", testcentre: ["North Eastern Indira Gandhi Institute of Health and Medical Sciences, Shillong"]},
    {state: "Odisha", testcentre: ["Regional Medical Research Centre, Bhubaneswar"]},
    {state: "Puducherry", testcentre: ["Jawaharlal Institute of Postgraduate Medical Education & Research, Puducherry"]},
    {state: "Punjab", testcentre: ["Government Medical College, Patiala", "Government Medical College, Amritsar"]},
    {state: "Rajasthan", testcentre: ["Sawai Man Singh Hospital, Jaipur", "Dr S N Medical College, Jodhpur", "Jhalawar Medical College, Jhalawar", "SP Medical College, Bikaner", "RNT Medical college, Udaipur"]},
    {state: "Tamil Nadu", testcentre: ["King’s Institute of Preventive Medicine & Research, Chennai", "Government Medical College, Theni", "Tirunelveli Medical College, Tirunelveli", "Government Medical College, Thiruvarur"]},
    {state: "Telangana", testcentre: ["Gandhi Medical College, Secunderabad", "Osmania Medical college, Hyderabad"]},
    {state: "Tripura", testcentre: ["Government Medical College, Agartala"]},
    {state: "Uttar Pradesh", testcentre: ["King George Medical University, Lucknow", "Institute of Medical Sciences, Banaras Hindu University, Varanasi", "Jawaharlal Nehru Medical College, Aligarh"]},
    {state: "Uttarakhand", testcentre: ["Government Medical College, Haldwani"]},
    {state: "West Bengal", testcentre: ["National Institute of Cholera and Enteric Diseases, Kolkata", "IPGMER, Kolkata"]},
]